cities.json

Added boundaries for Coimbra (PT), Faro (PT), Évora (PT)

Request for Coimbra (PT), Faro (PT), Évora (PT)

---

cities.json

see https://en.wikipedia.org/wiki/Metropolitan_municipalities_in_Turkey

adding 3 cities from Turkey: Adana, Bursa, Kayseri

---

cities.json

+ Penang, Malaysia
+ Banff, Canada
+ Bali, Indonesia
+ Cairns, Australia

Add 4 city extracts

---

cities.json

Not following convention city-name_country

Updated name Gold Coast, Australia

---

cities.json

corrected bbox
corrected decimals for circle ci tests

added Richmond VA and Providence RI, corrected last time!

---

cities.json

Please add this city to the list...

Novi Sad, Serbia

---

cities.json

Added bbox for two cities:
1. [Donetsk](https://en.wikipedia.org/wiki/Donetsk)
OSM Relation: [#1413957](https://www.openstreetmap.org/relation/1413957)
2. [Vinnytsia](https://en.wikipedia.org/wiki/Vinnytsia)
OSM Relation: [#361818](https://www.openstreetmap.org/relation/361818)

Added Ukrainian cities: Donetsk, Vinnytsia.

---

cities.json

Add some more significant cities from the metro area

Expand San Antonio, Texas

---

cities.json

Added Gothenburg, Sweden

---

cities.json

add Burgos, Spain

---

cities.json

Nottingham is a city in Nottinghamshire, UK with a population of around 300,000
http://en.wikipedia.org/wiki/Nottingham

Update cities.json to include Nottingham, England

---

cities.json

Adds 
- Derry, Ireland (#203)
- Ulyanovsk, Russia (#196)
- Kochi, India (#195)
- Tamale, Ghana (#197)

Adding new cities

---

cities.json

Adds:
- San Jose, CA (#200)
- Barnstable, MA (#199)
- Cordoba, Argentina (#225)
- Pisa, Italy (#201)
- Rouen, France (#204)
- Metz, France (#217)

More cities? More cities.

---

cities.json

Adds:
- Juba, South Sudan (#206)
- Brampton, Ontario (#210)
- Fallujah, Iraq (#211)
- Cairns, Australia (#212)
- Juneau, Alaska (#208)

So many cities!

---

cities.json

Added one city: Bruges, Belgium

Add Bruges, Belgium

---

cities.json

Added Cuneo, Piedmont Italy to cities.json

Added Cuneo, Piedmont Italy to cities.json

---

cities.json

Adds Cities
- Cebu (#231)
- Davao City (#231)
- Cagayan de Oro (#231)
- Sioux City (#234)
- Nancy, France (#237)
- Perpignan, France (#237)

Adds some cities

---

cities.json

Adds:
- Harrisburg, PA ( #239 )
- Avila, Spain (#240)
- Wichita, Kansas (#241)
- Orlando, Florida (#242)
- Donostia - San Sebastián, Spain (#250)

June 22 city additions 

---

cities.json

New city added: Donostia - San Sebastián. Thanks!

Add Donostia - San Sebastián (Spain)

---

cities.json

Adds:
- Saint Lucia (#251)
- Brighton, England (#245)
- Oxford, England (#243)
- Cambridge, England (#244)
- Turin, Italy (#247)
- Verona, Italy (#246)

June 24 City additions

---

cities.json

Adds: 
Modifies:
- Tianjin, China (#270)

July 30 cities

---

cities.json

Added Santa Cruz from the Pacific Ocean to Aptos, up to Ben Lomand.

Added Santa Cruz, CA

---

cities.json

havent been able to run the testsuite, since bundle/rake doesnt work ootb on OpenBSD where we can have multiple versions of ruby.

add Clermont Ferrand, France

---

cities.json

Adding Mariana, Minas Gerais, Brazil

---

cities.json

Add South Bend, Indiana

---

cities.json

Added Asheville, North Carolina

Added Asheville, North Carolina

---

cities.json

Adds:
- Tirana, Albania (#353)
- The Hague, Netherlands (#356)
- Dijon, France (#354)
- Bogor, Indonesia (#355)

December 17

---

cities.json

Add Florianopolis (Brazil) to cities

Add Florianopolis (Brazil) to cities

---

cities.json

Added  Dnipropetrovsk, Ukraine

---

cities.json

https://github.com/mapzen/metroextractor-cities/issues/379

solve issue "Hellertown, Pennsylvania #379"

---

cities.json

added beirut

---

cities.json

Adds:
- #392 Santigo do Campostela, Spain
- #388 
- Exatepec de Morelos, Mexico
- Juaréz, Mexico
- Tijuana, Mexico
- San Diego, California
- Leon, Mexico
- Cali, Colombia
- Manaus, Brazil
- Dortmund, Germany
- Essen, Germany
- Hanover, Germany
- Bochum, Germany
- Bielefeld, Germany
- Bonn, Germany
- Münster, Germany
- Maracaibo, Venezuela

February 04

---

cities.json

Updated to include the greater Chattanooga areas for an outdoor mapping project.

Chattanooga update

---

cities.json

Add-Iquique-Chile

---

docs/index.md

call for action at the top of documentation

---

docs/index.md

updated copy and survey link

---

docs/index.md

removing survey box at the top of the index
